### ISSUE TITLE
Training in debug mode

### ISSUE THREAD

**Issue by addadda023** [joeynmt/joeynmt#102]
**Describe the bug**
I want to train in debug mode in PyCharm (or VS code) to primarily inspect the structure of training data. How do I do this? 

**To Reproduce**

I added ../configs/small.yaml as argument for file training.py before running training.py in debug mode. My data is stored in the required directory, and the data is in pickle format, so I need to load it first. I get an error saying the file can't be found, which makes sense because the training.py can't see ./data/training_file.pkl. 
This is line 625 in training.py.
```
 # load the data
 train_data, dev_data, test_data, src_vocab, trg_vocab = load_data(
               data_cfg=cfg["data"])
```

**Comment by addadda023** [comment]
Potential solution: 
I updated data path to `../data` and ran training.py in debug mode. This forces training.py to go a folder up and then it can find `data` folder. I'd have to change the data path back to `./data` when I train without debug mode. Hope there is a better way to run in debug mode.

**Comment by addadda023** [comment]
I'm going to close this issue.

**Comment by juliakreutzer** [comment]
Hi @addadda023, did your solution work? 
Joey NMT does not work with data in pkl format, it has to be plaintext, and you have to point to it from the config file. Relative and absolute paths should both work.

**Comment by addadda023** [comment]
> Hi @addadda023, did your solution work?
> Joey NMT does not work with data in pkl format, it has to be plaintext, and you have to point to it from the config file. Relative and absolute paths should both work.

Hi @juliakreutzer, I had modified the pre-processing pipeline to take pkl. It ultimately provides the input as plaintext.
