### ISSUE TITLE
Occur RuntimeError when I execute translate

### ISSUE THREAD

**Issue by kadotani-ist** [joeynmt/joeynmt#104]
**Describe the bug**
When I execute "python3 -m joeynmt translate hoge", a following error message is displayed.

Error message:
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

**To Reproduce**
1. task description
I want to train a formality style transfer system from informal to formal on GYAFC Dataset (Entertainment_Music).
2. configuration file
[ezyzip.zip](https://github.com/joeynmt/joeynmt/files/5121747/ezyzip.zip)
3. code call
python3 -m joeynmt translate gyafc/Entertainment_Music/result/config.yaml

**Logged output**
[train.log](https://github.com/joeynmt/joeynmt/files/5121767/train.log)
[validations.txt](https://github.com/joeynmt/joeynmt/files/5121769/validations.txt)

**Expected behavior**
I expect this error message is not displayed and I can execute the code call.

**System (please complete the following information):**
 - OS: mac OS Catalina
 - CPU
 - Python Version 3.7.6

**Comment by CateGitau** [comment]
I had the same error and got rid of this bug by going to joeynmt/search.py and edit the line: topk_beam_index = topk_ids.div(decoder.output_size) to  topk_beam_index = topk_ids.floor_divide(decoder.output_size).

**Comment by kadotani-ist** [comment]
Thanks to your advice, I have solved the problem.

**Comment by juliakreutzer** [comment]
Thank you @CateGitau!! :100:
