### ISSUE TITLE
Joeynmt sees all available GPU devices but attempts to use memory of only 1 GPU. It complains CUDA out of memory

### ISSUE THREAD

**Issue by addadda023** [joeynmt/joeynmt#106]
**Describe the bug**
Available GPUS: 4 Tesla V100-SXM2 with 15.78GB RAM each. JoeyNMT sees it:
`2020-08-25 21:36:56.896921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0, 1, 2, 3`

During self.forward CUDA out of memory pops up:
`RuntimeError: CUDA out of memory. Tried to allocate 21.71 GiB (GPU 0; 15.78 GiB total capacity; 4.20 GiB already allocated; 10.50 GiB free; 4.21 GiB reserved in total by PyTorch)`

How does JoeyNMT utilizes availability of multiple GPUs? 

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - CPU / GPU
 - Python Version: 3.6.9
- CUDA 10.1

```>>> nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:04:00.0 Off |                    0 |
| N/A   33C    P0    39W / 300W |      0MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:05:00.0 Off |                    0 |
| N/A   30C    P0    38W / 300W |      0MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:09:00.0 Off |                    0 |
| N/A   29C    P0    39W / 300W |      0MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:89:00.0 Off |                    0 |
| N/A   28C    P0    38W / 300W |      0MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by juliakreutzer** [comment]
Hi @addadda023,
Joey NMT does currently not support multi-GPU processing. To select the GPU that you want to run it on, set the `CUDA_VISIBLE_DEVICES` environment variable accordingly.

**Comment by addadda023** [comment]
Hi @juliakreutzer, thanks for the reply. It seems JoeyNMT doesn't support both data and model parallelism. 

For data parallelism, pytorch offers [DataParallel](https://pytorch.org/docs/master/generated/torch.nn.DataParallel.html) module. However, when wrapping the model with `nn.DataParallel`, we lose model parameters that are used in `training.py`, eg., `self.model.pad_index`, `self.model.bos_index`, `self.model.state_dict()`, etc. I can still access them using `self.model.module.txt_property`, but I have to be careful altering these values though:

> In each forward, module is replicated on each device, so any updates to the running module in forward will be lost. For example, if module has a counter attribute that is incremented in each forward , it will always stay at the initial value because the update is done on the replicas which are destroyed after forward .

Any guidance in making data parallelism working would be appreciated.

**Comment by juliakreutzer** [comment]
Hi @addadda023,

thanks, the DataParallel and the [DistributedParallel](https://pytorch.org/docs/master/generated/torch.nn.parallel.DistributedDataParallel.html#distributeddataparallel) seem like a good solution.

I just learned that May (@may-) has implemented a multi-gpu solution with DataParallel, you can find it [here](https://github.com/may-/joeynmt/tree/multi-gpu). Maybe try that?

**Comment by addadda023** [comment]
Thanks @juliakreutzer That's excellent!!
