### ISSUE TITLE
“Early stopping” with accuracy metric does not work 

### ISSUE THREAD

**Issue by Simon-Will** [joeynmt/joeynmt#110]
When configuring a model with `eval_metric: 'sequence_accuracy'` and `early_stopping_metric: 'eval_metric'` in the training section, Joey thinks a small sequence accuracy is desirable and will (usually) only save a checkpoint only at the first validation time since the accuracy is still small at this time and will grow with training the model further.

This is due to the following code in [`training.py`](https://github.com/joeynmt/joeynmt/blob/abb5d3f379de957c24f41d784c18000cdda40198/joeynmt/training.py):

```python

        # if we schedule after BLEU/chrf, we want to maximize it, else minimize
        # early_stopping_metric decides on how to find the early stopping point:
        # ckpts are written when there's a new high/low score for this metric
        if self.early_stopping_metric in ["ppl", "loss"]:
            self.minimize_metric = True
        elif self.early_stopping_metric == "eval_metric":
            if self.eval_metric in ["bleu", "chrf"]:
                self.minimize_metric = False
            # eval metric that has to get minimized (not yet implemented)
            else:
                self.minimize_metric = True
        else:
            raise ConfigurationError(
                "Invalid setting for 'early_stopping_metric', "
                "valid options: 'loss', 'ppl', 'eval_metric'.")
```

By the way, actual early stopping (i.e. training begin stopped if the patience is exhausted) is not implemented yet, right? Is this an open TODO?

**Comment by Simon-Will** [comment]
Since the fix for this, is only a small change, I’m going to submit a pull request in a moment.

**Comment by juliakreutzer** [comment]
Thanks for spotting and fixing this!
