### ISSUE TITLE
Support for pre-trained wordembedding

### ISSUE THREAD

**Issue by LinuxBeginner** [joeynmt/joeynmt#112]
Does joyenmt support pre-trained wordembedding like the one in [OpenNMT-py](https://opennmt.net/OpenNMT-py/FAQ.html)?

Thanks.

**Comment by juliakreutzer** [comment]
Currently not. It shouldn't be very hard to integrate, though!

**Comment by may-** [comment]
Hi @LinuxBeginner,

I implemented this. Please check my pull request #135.
I hope it's not too late...

**Comment by juliakreutzer** [comment]
The code is merged.
