### ISSUE TITLE
RuntimeError: index_select(): Expected dtype int64 for index

### ISSUE THREAD

**Issue by Sridhar98** [joeynmt/joeynmt#118]
**Describe the bug**
Runtime error while training using bandit-joeynmt fork, acl19 branch.

**To Reproduce**
1. Run the train script with data from bandit-joeynmt/test/data/reverse
2. configuration file: reverse.yaml
3. code call: !python3 training.py /content/drive/My\ Drive/IIITH/regulator/bandit-joeynmt/configs/reverse.yaml

**Logged output**
Traceback (most recent call last):
  File "training.py", line 1256, in <module>
    train(cfg_file=args.config)
  File "training.py", line 1228, in train
    beam_size=beam_size, beam_alpha=beam_alpha)
  File "/usr/local/lib/python3.6/dist-packages/joeynmt/prediction.py", line 66, in validate_on_data
    max_output_length=max_output_length)
  File "/usr/local/lib/python3.6/dist-packages/joeynmt/model.py", line 1379, in run_batch
    decoder=self.decoder)
  File "/usr/local/lib/python3.6/dist-packages/joeynmt/search.py", line 208, in beam_search
    [alive_seq.index_select(0, select_indices),
RuntimeError: index_select(): Expected dtype int64 for index

**Additional Information**
select_indices parameter in the call to index_select() is a tensor of float values, but a tensor of integers is expected.

**System - Using Google Colab:**
 - GPU
 - Python Version: 3.6.9

**Comment by Sridhar98** [comment]
Hi @juliakreutzer 
Is any more information needed from my side?

**Comment by juliakreutzer** [comment]
Hi @Sridhar98 which PyTorch version are you running this on? 
The acl-19 branch hasn't been updated, so it's probably some version issue.

**Comment by Sridhar98** [comment]
Thank you @juliakreutzer. It was a PyTorch version issue. I was using version 1.7.0 (the latest version that comes with Colab by default). Downgrading to 1.4.0 solved my issue

**Comment by juliakreutzer** [comment]
Awesome thanks!
