### ISSUE TITLE
get_iwslt14_bpe.sh broken after link changed

### ISSUE THREAD

**Issue by nbrgr** [joeynmt/joeynmt#129]
The link that the script `get_iwslt14_bpe.sh` uses to download the data is broken and now leads to a 404 page. They moved the hosting of the data to a google drive, which I don't think you can access with curl. Additionally, the tgz file on google drive is all languages so some of the logic will need to be re-written. Since I need to use this data, I'll try to write a new script for the iwslt14 data.

**Comment by juliakreutzer** [comment]
Thanks @nbrgr! In case this does not work at all automatically, it might be worth hosting a copy exactly for that language pair on the Heidelberg site with the pretrained joeynmt models.

**Comment by nbrgr** [comment]
That's a good idea, I'll see if we can host it. I checked and the facebook fairseq script for it works but they changed the url to something they're self hosting so we could adapt that.

**Comment by juliakreutzer** [comment]
@nbrgr any update regarding the hosting?

**Comment by may-** [comment]
How about using `torchtext.datasets`? or do we rather want to avoid torchtext dependency? https://github.com/pytorch/text/blob/master/torchtext/datasets/iwslt2016.py (not supported in torchtext v0.8.1)

I personally think better to outsource the data link (and download logic) maintenance...

**Comment by nbrgr** [comment]
I found that facebook was actually hosting the same dataset in their fairseq repo and had a script to preprocess it. 
[prepare-iwslt14.sh](https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-iwslt14.sh) also uses iwslt14 de->en, moses tokenizer, and subword-nmt for BPEs.

**Comment by juliakreutzer** [comment]
Could you please update the link to that new fairseq-provided location then @nbrgr ? 

Torchtext datasets have the benefits of having clearly defined splits, but I'm not sure how much overhead it would be to make our datasets compatible.

**Comment by nbrgr** [comment]
I wanted to make sure that linking to the facebook hosted version was okay with you, so I've just made a pull request now #140

**Comment by juliakreutzer** [comment]
Resolved with #140
