### ISSUE TITLE
init_hidden 

### ISSUE THREAD

**Issue by yokusama** [joeynmt/joeynmt#13]
Hi,
I have a question about the init_hidden in decoder.
I can understand  "only feed the final state of the top-most layer to the decoder".
But,  the hidden state and cell state of LSTM  have different meaning ?
So is it appropriate to initialize the decoder with " (h, h) if isinstance(self.rnn, nn.LSTM) " ?

**Comment by juliakreutzer** [comment]
Hi @yokusama
Good question! We don't have experimental evidence to answer your question yet, but I'll start an experiment to compare the benchmark results with zero initialization of the memory state.

**Comment by yokusama** [comment]
Thanks for your reply!
By the way, fairseq and opennmt initialize the decoder with encoder final hidden state/cell state (directions*layers x batch x hidden ).
In my personal experience, zero initialization is a little bad.

**Comment by juliakreutzer** [comment]
Yes, that's another option (with more parameters). Will try both :)

**Comment by juliakreutzer** [comment]
Okay, so I repeated the benchmark experiments on [WMT en-de](https://github.com/joeynmt/joeynmt/blob/master/README.md) with a separate learned initialization of the memory cell and a zero memory cell initialization (the initialization of the state is still learned):

| memory cell init type | dev BLEU | test BLEU | #Params |
| --------------------------- | ----- | ----- | ---- |
| c = h (current master) | 24.33 | 23.45 | 86.37M |
| c = 0 | 24.89 | 23.35 | 86.37M |
| c = FF(encoder_c) | 24.86 | 23.61 | 87.38M |

According to these results the initialization of the memory cell doesn't have a large influence in this setup. The results for the learned initialization are a tiny bit better, but the model grows in size and learning takes longer.

Still to evaluate: simply copying the encoder memory cell (if same size).

**Comment by yokusama** [comment]
Thank you very much for your experiment!!
This has been bothering me for a long time, and it seems that there is no standard way of initialization!
Maybe learning time is more important for me! \(^o^)/
