### ISSUE TITLE
joeyNMT 1.1/Google Colab - uses device:cpu instead of GPU 

### ISSUE THREAD

**Issue by cdleong** [joeynmt/joeynmt#133]
**Problem**
When training using Masakhane custom data notebook, and pip installing joeyNMT, 
`!cd joeynmt; python3 -m joeynmt train configs/transformer_$src$tgt.yaml` uses CPU instead of GPU. 

This occurs if I use version 1.1, but NOT if I pip install 1.0 specifically. 

* If I use `joeynmt==1.0` when pip installing, I get `device:cuda`
* If I use `joeynmt` when pip installing, it installs 1.1, and I get `device:cpu`

**System (please complete the following information):**
 - Google Colab, https://github.com/masakhane-io/masakhane-mt/blob/master/starter_notebook-custom-data.ipynb
 - joeyNMT pip installed

**Comment by turkicinterlingua** [comment]
same issue! It has something to do with the torch version I believe but not sure yet

**Comment by juliakreutzer** [comment]
Installing joeynmt v1.1 results in torch v1.6.0 for CPU being installed:

´Collecting torch==1.6.0
  Downloading https://files.pythonhosted.org/packages/38/53/914885a93a44b96c0dd1c36f36ff10afe341f091230aad68f7228d61db1e/torch-1.6.0-cp36-cp36m-manylinux1_x86_64.whl (748.8MB)´

and the existing GPU-enabled version is uninstalled:
´Found existing installation: torch 1.7.0+cu101
    Uninstalling torch-1.7.0+cu101:
      Successfully uninstalled torch-1.7.0+cu101´

Will update you on progress on fixing this.

**Comment by juliakreutzer** [comment]
Please try installing pytorch 1.7.1 with CUDA in addition to Joeynmt from pip:
`! pip install torch==1.7.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html`

I upgraded torch to 1.7.1 since May reported it works well with torchtext v0.8.1.

**Comment by bricksdont** [comment]
There is a deprecation warning about a specific class in torchtext:

```
/net/cephfs/scratch/mathmu/amit/venvs/joey3/lib/python3.7/site-packages/torchtext/data/field.py:150: UserWarning: Field class will be retired in the 0.8.0 release and moved to torchtext.legacy. Please see 0.7.0 release notes for further information.
  warnings.warn('{} class will be retired in the 0.8.0 release and moved to torchtext.legacy. Please see 0.7.0 release notes for further information.'.format(self.__class__.__name__), UserWarning)
```
  
Is this perhaps a problem when updating the requirements to torchtext==0.8.1 ?

**Comment by juliakreutzer** [comment]
Yes, the torchtext dependency needs to get refactored (#7). So far I haven't encountered problems running the code though, have you? 
@may- you said you were successful in running it under this condition, right?

**Comment by bricksdont** [comment]
No, I have not run into problems related to torchtext. I guess that if there are no problems then the `Field` class can be imported as usual, even if it is now actually in `torchtext.legacy`. So, all fine it seems 👍 .

**Comment by cdleong** [comment]
> 
> 
> Please try installing pytorch 1.7.1 with CUDA in addition to Joeynmt from pip:
> `! pip install torch==1.7.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> I upgraded torch to 1.7.1 since May reported it works well with torchtext v0.8.1.

Changed the installation cell in Custom Data notebook like so: 
```
# Install JoeyNMT
! rm -r joeynmt
! git clone https://github.com/joeynmt/joeynmt.git
# ! cd joeynmt; pip3 install .

# ! pip install joeynmt  #Colin: causes issues
#! pip install joeynmt==1.0
! pip install joeynmt==1.1
! pip install torch==1.7.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html 
```

Alas, I now get installation errors

![image](https://user-images.githubusercontent.com/4109253/105063368-a60e4e80-5a49-11eb-9ee3-51c025370578.png)

And when I try to run the training cell I get a ContextualVersionConflict:

![image](https://user-images.githubusercontent.com/4109253/105063489-ca6a2b00-5a49-11eb-9b6f-3f2b2fca7579.png)

I'll try again with `pip install joeynmt` instead of specifying a version, see if that makes a difference

**Comment by cdleong** [comment]
OK, If I DON'T specify the joeyNMT version it installs v 1.2, which works with the CUDA version of torch:
```
# Install JoeyNMT
! rm -r joeynmt
! git clone https://github.com/joeynmt/joeynmt.git
# ! cd joeynmt; pip3 install .

# ! pip install joeynmt  #Colin: causes issues
#! pip install joeynmt==1.
# ! pip install joeynmt==1.1
! pip install joeynmt
! pip install torch==1.7.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html 
```

**Comment by bricksdont** [comment]
Julia has shipped version 1.2 to PyPi a few hours ago:

https://pypi.org/project/joeynmt/#history

that is why `pip install joeynmt` now installs version 1.2.

Regarding your error messages: I think it's impossible to know what exactly you executed in which order, and if perhaps joeynmt or any other library was already installed when you attempted to install other versions.

Cloning the Github repo should also work. i.e. two ways to install that both work in a notebook where nothing else was executed so far are:

```
git clone https://github.com/joeynmt/joeynmt.git
cd joeynmt; pip3 install .
pip3 install torch==1.7.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
```

or

```
pip3 install joeynmt
pip3 install torch==1.7.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
```

------

If you do any of those two, the torch library that is already installed in every Colab notebook will be uninstalled because it is version 1.7.0. You can check this by running the following in a new Colab notebook:

    !pip show torch

Output:

    Name: torch
    Version: 1.7.0+cu101

**Comment by cdleong** [comment]
@bricksdont forgot to mention I've been doing "factory reset" on the Colab notebook each time when testing, in the hopes that that would give me a consistent environment on the error messages. So each time I ran the installation cell, it was with a fresh notebook. 

I didn't know how to check the torch version before, that's really useful, thank you!

**Comment by cdleong** [comment]
I hadn't thought to check cloning/installing yet, since joeyNMT 1.2 came out. I will try that, and also try just installing 1.2 directly, see if I still have GPU issues

**Comment by cdleong** [comment]
Tried different methods, did a "factory reset runtime" on the Colab notebook each time. 
- clone and pip install repo, do not install torch -> uses `device:cpu`
- clone and pip install repo, `pip3 install torch==1.7.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html` -> `device:cuda`
- `pip install joeyNMT`, do not install torch specifically -> `device:cpu`
-

**Comment by juliakreutzer** [comment]
Thanks @bricksdont for the help and @cdleong for testing this systematically! I'm closing the issue now, but please re-open if you encounter any more problems in this direction.
