### ISSUE TITLE
expected behavior for `keep_last_ckpts = -1`

### ISSUE THREAD

**Issue by may-** [joeynmt/joeynmt#136]
Hi @juliakreutzer,

I wanted to save ckpts at every validation step regardless of early-stopping-metric score, so I set `keep_last_ckpts = -1`, according to the description here:

https://github.com/joeynmt/joeynmt/blob/46b2fe3b05638728413ee5bae6a347411175c3c5/configs/small.yaml#L67

But joeynmt didn't save ckpts at all in that case. Actually, the TrainManager doesn't call `_save_checkpoint()` func if `keep_last_ckpts` is less than or equal to zero (queue with infinite length: https://docs.python.org/3/library/queue.html).
https://github.com/joeynmt/joeynmt/blob/46b2fe3b05638728413ee5bae6a347411175c3c5/joeynmt/training.py#L98-L99
https://github.com/joeynmt/joeynmt/blob/46b2fe3b05638728413ee5bae6a347411175c3c5/joeynmt/training.py#L544-L547

What is the expected behavior? You indeed intended no save action if `keep_last_ckpts = -1`, that is, the description in config was wrong or can we change the code so that ckpts will be saved every time if `keep_last_ckpts = -1`?

**Comment by juliakreutzer** [comment]
Hi @may- thanks for spotting this bug! The description in the config is indeed incorrect, but I think it describes the desired behavior. How about extending that if statement by an `or keep_last_ckpts == -1` (with correct reference to `keep_last_ckpts` of course).

**Comment by may-** [comment]
Hi @juliakreutzer, thank you for your reply. I understand your intention. In the latest version, we have `save_latest_checkpoint` flag. what is the difference, `save_latest_checkpoint: True` and `keep_last_ckpts: -1`, then? (maybe I should ask @nbrgr, who has introduced this flag, recently)

**Comment by may-** [comment]
It's a bit different point, but I write here together in this thread:

`keep_last_ckpts: 3` means neither `last` nor `best`, actually. Consider the following case:
```
       steps 1000 bleu 10.0  *
       steps 2000 bleu 11.0  *
       steps 3000 bleu 10.5  
       steps 4000 bleu 11.5  *
       steps 5000 bleu 10.2
       steps 6000 bleu 11.2
```
current setup saves `1000.ckpt`, `2000.ckpt`, `4000.ckpt`, but the **best** 3 ckpts are `2000.ckpt`, `4000.ckpt` and `6000.ckpt`. So, I'm wondering if the current behaviour is really optimal for most of the users. (for instance, often suggested taking average of best or last ckpts => want to call `scripts/average_checkpoints.py 2000.ckpt 4000.ckpt 6000.ckpt` or `scripts/average_checkpoints.py 4000.ckpt 5000.ckpt 6000.ckpt`, but taking avg of `1000.ckpt`, `2000.ckpt`, and `4000.ckpt` sounds uncommon to me.) Why don't we keep the **best** ckpts?

But I guess you intentionally designed the saving behavior so that joeynmt will save the ckpt every time it reached the best eval-metric score, didn't you? I'm not sure what the users actually want in most cases. How do you think?

**Comment by may-** [comment]
maybe we can keep the current saving behavior with `save_latest_checkpoint` flag, but change the deletion logic so that we delete the ckpts only when `keep_last_ckpts > 0`. More specifically, unlike `maxsize` in `queue.Queue`, `maxlen` in `collections.deque` should take None instead of 0 when the queue length is unbounded, according to the official python doc. So the deletion logic would be
```
if self.ckpt_queue.maxlen is not None:
    delete action ...
```

we can keep all ckpts by setting in cfg:
```
save_latest_checkpoint: True # save ckpt at every validation time
keep_last_ckpts: -1          # no ckpt will be deleted
```

How do you think, @juliakreutzer ?

**Comment by juliakreutzer** [comment]
Yes, you're completely right. The current option was chosen for the ease of implementation and it still guarantees having the one best model in the end. But users will probably want the k best ones, and not those when the model makes a big improvement. 
We'd have to switch to a quality- rather than time-guided queue, i.e. always keep the best k in the queue (and the most recent one) and remove the rest.

Your last suggestions sounds good to me for the original (not saving all checkpoints) issue. :+1:

**Comment by may-** [comment]
I'm testing this bug fix, and have several questions.

- If `save_latest_checkpoint: False` and `keep_last_ckpts: 5`(or some positive integer), then just as before, nothing changed.
- If `save_latest_checkpoint: True` and `keep_last_ckpts: -1`, then save weights in each vaildation, no ckpts deleted.
- If `save_latest_checkpoint: True` and `keep_last_ckpts: 5`(or some positive integer), what supposed to be then? Currently, `keep_last_ckpts` is just ignored and only the latest ckpt kept. (Is it true, @nbrgr ?) Do we expect this behavior? I think it's a bit counter-intuitive. If I see `save_latest_checkpoint: True` and `keep_last_ckpts: 5`, I expect the last 5 ckpts will be kept.

How do you think, @juliakreutzer ? You said the current option was chosen for the ease of implementation and we'd have to switch to a quality- rather than time-guided queue. Maybe, now it's time to switch, I guess. I mean, I'm ready to implement the one we really want to have. So I'd like to discuss the concrete specification for it, before I start.

**Comment by juliakreutzer** [comment]
Hi @may- totally agreed, it's time to change that now. I thought more on this and I am not completely convinced we should make it a binary choice. For continuing training after e.g. a job crashed, it might be important to always have the most recent checkpoint saved. And then we need the best one(s) for testing. Do you think there's a way to combine it? It might make it more complex, but perhaps it's worth it.
Suggestion:
- `keep_last_ckpts`: n, default=1, with a symbolic link `last.ckpt` to load during continued training
- `keep_best_ckpts`: n, default=1, with a symbolic link `best.ckpt` to load during inference
In this way we'd always have the last and the best checkpoint and they might not be identical. It would require having separate queues. What do you think?

**Comment by may-** [comment]
yeah, it sounds good. we could have multiple queues, but then a bit complicated to handle mis-specifications such as keep_last_ckpts=-1 and keep_best_ckpts=10, no? Although we can return a configuration error and abort the process, but I feel a bit too harsh, especially when I see such a config error after I waited for huge data loaded...

if the usage for the latest ckpt is almost limited to resume the interrupted training, how about saving the latest ckpt always by default without any option? and we always use "best" criterion to determine the number of ckpts to save/delete? Of course, we change the "best" logic so that really best n models will be saved. For instance, in the following case, best 3 means [4000, 6000, 2000], instead of the ckpts with `*`. Even though the step 6000 doesn't beat the best bleu sofar, but still better than the worst one in the queue, so we update our queue. Then it's more likely that relatively newer ckpts will be kept.
```
       steps 1000 bleu 10.0  *
       steps 2000 bleu 11.0  *
       steps 3000 bleu 10.5  
       steps 4000 bleu 11.5  *
       steps 5000 bleu 10.2
       steps 6000 bleu 11.2
```

maybe it's rather my personal preference. Misspecification can happen whatever we define for this option. Two separate queues for `best` and `last` sounds reasonable to me.

**Comment by juliakreutzer** [comment]
Yes you're right, it's not we'll defined when both queues are overlapping. I like your simplification idea: save the most recent one plus any additional best checkpoints. I think this fits the practical use cases in the best way without creating confusion👍
