### ISSUE TITLE
Joey NMT for paper Correct Me If You Can

### ISSUE THREAD

**Issue by AmanSinghal927** [joeynmt/joeynmt#137]
I am trying to replicate the results presented in the paper "Correct Me If You Can". I am using Google Colab. I have already cloned the Joey NMT repo as well as Downloaded the model into the same location. I notice that for the toy models a few shell scripts are present to evaluate the toy models. However, I am unclear how I can evaluate the WMT17 en-de model. Can someone please help?

**Comment by bricksdont** [comment]
Copying my comment (from https://github.com/bricksdont/joeynmt-toy-models/issues/2) here:

> Please make sure you include a link to your Colab, and also explain more clearly what your problem is with evaluation.

**Comment by juliakreutzer** [comment]
@AmanSinghal927 https://github.com/joeynmt/joeynmt#1-test-set-evaluation here's a short description how to run JoeyNMT in testing mode. You need to point to the configuration of the model that you'd like to test and make sure the correct test data is listed in the configuration.
