### ISSUE TITLE
possibly a bug in PullRequest #139 (N-best candidates)?

### ISSUE THREAD

**Issue by may-** [joeynmt/joeynmt#144]
Hi @sjarmero,

After your pull request #139 has been merged, I've got an error at https://github.com/joeynmt/joeynmt/blob/eb29133ec8662c9d9520d6a72b8888d84a90cc80/joeynmt/prediction.py#L114

It should look like this, maybe?
```python
assert len(sort_reverse_index) == batch.nseqs
```

---

and a small problem here, too.

https://github.com/joeynmt/joeynmt/blob/eb29133ec8662c9d9520d6a72b8888d84a90cc80/joeynmt/prediction.py#L131-L136

because now you use `append`, not `extend` as before,  `valid_attention_scores` wil become non-empty even if `attention_scores` is None, and it unexpectedly triggers this if-block:

https://github.com/joeynmt/joeynmt/blob/eb29133ec8662c9d9520d6a72b8888d84a90cc80/joeynmt/prediction.py#L355-L364

---

thank you for your effort to include the nbest list!

@juliakreutzer, FYI

**Comment by juliakreutzer** [comment]
thanks @may- ! 
I think your first suggestion is correct.
For the second case, we could check the length instead. I guess the attention plots should also not get saved for all n-best...

**Comment by aitorme** [comment]
hi there,
can a pull request be created to fix line 114 in prediction.py as @may- suggested, so newcomers to joeynmt don't run into this?
Thanks!

**Comment by sjarmero** [comment]
Hi @aitorme That line has been corrected in Pull Request https://github.com/joeynmt/joeynmt/pull/145, which has not been merged yet

**Comment by may-** [comment]
@juliakreutzer how about just accepting the @sjarmero 's pull request for now? It seems a lot of people are waining this fix. we can add a unit test a bit later.

**Comment by juliakreutzer** [comment]
Fine with me! I'll do that.
