### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by nicola-decao** [joeynmt/joeynmt#148]
Is this line correct?
https://github.com/joeynmt/joeynmt/blob/42ad5889c622e2583b667cc58bc7c37f3c99111c/joeynmt/search.py#L336

That means we stop an entire beam only when the top-1 predicts EOS. This seems wrong as it may happen that some other hypotheses in the beam will produce longer sequences with a higher score.

**Comment by juliakreutzer** [comment]
fixed in #153
