### ISSUE TITLE
Sharing pre-trained models through Hugging Face

### ISSUE THREAD

**Issue by osanseviero** [joeynmt/joeynmt#159]
Hi there! This project is awesome 🚀 

Would you be interested in sharing your pre-trained models in the [Hugging Face Hub](http://hf.co/models)? The Hub offers free hosting of over 25K models, and it would make your work more accessible and visible to the rest of the ML community.  We can help you set up a joeynmt organization or filter for people to easily discover all joeynmt models and enable the community to easily share their own models.

Some of the benefits of sharing your models through the Hub would be:
* versioning, commit history and diffs
* repos provide useful metadata about their tasks, languages, metrics, etc that make them discoverable
* multiple features from TensorBoard visualizations, PapersWithCode integration, and more
* wider reach of your work to the ecosystem

Creating the repos and adding new models should be a relatively straightforward process if you've used Git before. This is a [step-by-step guide](https://huggingface.co/docs/hub/adding-a-model) explaining the process in case you're interested. There's also a Python library for programmatic access to models in the Hub.

Please let us know if you would be interested and if you have any questions.

Happy to hear your thoughts,
**Omar and the Hugging Face team**

**Comment by juliakreutzer** [comment]
https://huggingface.co/spaces/chrisjay/masakhane-benchmarks

**Comment by osanseviero** [comment]
Hi! Yes, Chris was able to do this integration but using a fork of this repo (https://github.com/chrisemezue/joeynmt). Would be cool to get this integrated/merged here :) cc @chrisemezue

**Comment by juliakreutzer** [comment]
Awesome, thank you @chrisemezue! Can you send a PR?

**Comment by chrisemezue** [comment]
> Awesome, thank you @chrisemezue! Can you send a PR?

Okay. On it.

**Comment by chrisemezue** [comment]
#164 
Done

**Comment by juliakreutzer** [comment]
Thanks! I requested some changes, once they are resolved we can merge.

**Comment by ShadowVicky** [comment]
Hi I am getting an  error "No module named 'torchtext.legacy". I can't fix it. Please help me

**Comment by chrisemezue** [comment]
@ShadowVicky this was talked about [here](https://github.com/joeynmt/joeynmt/pull/164#issuecomment-1092808114).
__TLDR:__  install these specific versions
```
torchtext==0.9.0
torch==1.8.0
```

**Comment by may-** [comment]
See #213
