### ISSUE TITLE
Newly  face this error. Help me

### ISSUE THREAD

**Issue by ShadowVicky** [joeynmt/joeynmt#178]
100% 4000/4000 [00:25<00:00, 154.86it/s]
/bin/bash: test.en: No such file or directory
/bin/bash: test.as: No such file or directory
bpe.codes.4000	dev.bpe.en     test.en-as.en  train.bpe.en
dev.as		dev.en	       train.as       train.en
dev.bpe.as	test.en-as.as  train.bpe.as
bpe.codes.4000	dev.bpe.as  dev.en  test.en-as.as  train.as	 train.bpe.en
dev.as		dev.bpe.en  models  test.en-as.en  train.bpe.as  train.en
/content/joeynmt/scripts/build_vocab.py: line 4: $'\nBuild a vocab file\n': command not found
/content/joeynmt/scripts/build_vocab.py: line 5: import: command not found
/content/joeynmt/scripts/build_vocab.py: line 6: import: command not found
/content/joeynmt/scripts/build_vocab.py: line 7: import: command not found
from: can't read /var/mail/collections
from: can't read /var/mail/pathlib
from: can't read /var/mail/typing
/content/joeynmt/scripts/build_vocab.py: line 12: import: command not found
from: can't read /var/mail/subword_nmt
/content/joeynmt/scripts/build_vocab.py: line 15: syntax error near unexpected token `('
/content/joeynmt/scripts/build_vocab.py: line 15: `from joeynmt.constants import ('
BPE Test language Sentences
joeynmt/data/enas
tail: cannot open 'test.bpe.as' for reading: No such file or directory
Combined BPE Vocab
tail: cannot open 'joeynmt/data/enas/vocab.txt' for reading: No such file or directory

**Comment by may-** [comment]
Hi,

Can you tell us what command you used to invoke the script? I suspect the system triggers a wrong python executable, maybe? What returns `which python`?

We recommend to create a virtual env for joeynmt to isolate the dependencies.

**Comment by may-** [comment]
I close this for now. See https://github.com/joeynmt/joeynmt/pull/181. Please reopen it if you still have the problem.
