### ISSUE TITLE
Assertion error on build_vocab.py

### ISSUE THREAD

**Issue by kritisingh24** [joeynmt/joeynmt#186]
**Describe the bug**
Following the [colab repository](https://github.com/joeynmt/joeynmt/blob/main/notebooks/quick-start-with-joeynmt2.ipynb). I have created my own configuration based on plain text but I am getting this error:
```
Traceback (most recent call last):
  File "build_vocab.py", line 342, in <module>
    main(args)
  File "build_vocab.py", line 269, in main
    **cfg["data"].get("dataset_cfg", {}),
  File "/usr/local/lib/python3.7/dist-packages/joeynmt/datasets.py", line 555, in build_dataset
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/joeynmt/datasets.py", line 144, in _init_
    random_subset=random_subset,
  File "/usr/local/lib/python3.7/dist-packages/joeynmt/datasets.py", line 49, in _init_
    assert self.has_trg
AssertionError
```

**To Reproduce**
1. task description - "I want to train a translation system from English to Hindi on custom data"
2. [configuration file](https://gist.github.com/kritisingh24/678de0d4032de1f2b6383a127aca3e3b)
3. code call - python build_vocab.py {data_dir}/config.yaml

**Logged output**
If possible, please add the training log and validation reports or excerpts of them.  --- NA

**Expected behavior**
A clear and concise description of what you expected to happen. If dataset_type = plain is provided then dataset__cfg should not get any error. As described in [transformer_small.yaml](https://github.com/joeynmt/joeynmt/blob/main/configs/transformer_small.yaml)

**System (please complete the following information):**
 - OS: [e.g. iOS] : Colab
 - CPU / GPU : Colab
 - Python Version : 3.7

**Additional context**

**Comment by may-** [comment]
Hi @kritisingh24,

Thank you for reporting an error.

I suspect your input data `/content/drive/MyDrive/datasets_enhi/train.tok.hi` doesn't exist. Could you please check it?

You specified `tokenizer_type = subword-nmt` in build_vocab.py, it implies the script will train a subword-nmt tokenization model on the training data, and apply the model on the data. That is, your input data must contain raw sentences before tokenizetion. So I guess your raw data file before tokenization would be named as `train.en` and `train.hi` respectively, not "tok" version, maybe? I mean, it should be `train = /content/drive/MyDrive/datasets_enhi/train`, not `train = /content/drive/MyDrive/datasets_enhi/train.tok` in the config file, in that case.

If all the data files under the specified paths in config actually exist but still you encounter this error, your data files might have a problem, i.e. empty lines, wrong encoding, etc. Could you please share a small subset of `train.en` and `train.hi` with us (just a few sentences per file)? If `dataset_type = plain`, then joeynmt expects one-sentence-per-line format in each input file.

**Comment by kritisingh24** [comment]
Hi, @may-,

Thank you for getting back to me. I caught the error and found it was a silly mistake therefore I closed it. 

I am running into a very bad situation where the joeynmt model is not learning at all, I think it would be helpful if you can provide some direction. I have started to use tatoeba for en-hi from hugging face. The model doesn't seem to converge [log](https://gist.github.com/kritisingh24/7ad64fd8b04e4c110cc9911f70ba3457). I think there is some issue with the [configuration file](https://gist.github.com/kritisingh24/41cd878cbc3f7d57a2bd08b7901f7de2) that I have created. As I am trying to replicate a work previously [done](https://github.com/PrathyushaBajanthri/DS_Portfolio/blob/master/deep_learning/low_resource_language_translation/en_hi_experiments/en_hi_baseline.ipynb) by a friend on joeynmt version 2.
Also, the build_vocab.py runs subword-nmt and tokenization, the tokenization feature sometimes does not work for languages such as Hindi as I am using IndicNLP to do tokenization, how do you add this in version 2 when you generated the vocab?

Thanks,
Kriti

**Comment by may-** [comment]
Hi @kritisingh24,

The first thing I realized in your log is that your dataset size is too small to get a reasonable results.
I see only 9k taining data, which wouldn't be sufficient. Please consider to gather more parallel data. For example, [CC Matrix](https://opus.nlpl.eu/CCMatrix.php) in [Opus](https://opus.nlpl.eu/) has 15M hi-en pairs. In the log of your friend's work, I see 50k training data. Can you maybe get that 50k data from your friend?

Do you use by any chance the Helsinki-NLP's tatoeba corpus?  I don't know from where Huggingface's tatoeba corpus builder downloads the data, but I've heard from several people that the data in https://github.com/Helsinki-NLP/Tatoeba-Challenge partially has a problem with sentence alignment in some languages. I don't know well for en-hi pair (maybe they fixed the problem in the latest version? I haven't checked.), though.

I'll look into more details, but in the meantime please 
1. double check if your data (especially sentence alignment) looks ok,
2. increase the training datasize, and
3. make sure that you use the latest [official version of joeynmt](https://github.com/joeynmt/joeynmt).  (maybe you can try to cherry-pick the latest pull request, too: https://github.com/joeynmt/joeynmt/pull/181. I fixed some bugs there. They are not merged to the main branch yet but at least, I tested those fixes. On the other hand, the version from [my personal repo](https://github.com/may-/joeynmt) could be buggy, I commit there some experimental stuff without guarantee if it works.)

**Comment by may-** [comment]
Hi @kritisingh24,

I've wrote a notebook for tokenizer integration.
https://github.com/may-/joeynmt/blob/main/notebooks/tokenizer_tutorial_en.ipynb

I hope it will help a bit.

May

**Comment by JuliusFx131** [comment]
I faced the same problem. This helped me out:

```
from datasets import Features, Value, Translation

# Define the new feature schema, including both 'ID' and 'translation'
features = Features(
    {
        'ID': Value('string'),  # Adjust the type as necessary, e.g., 'int64' if it's an integer
        'translation': Translation(
            languages=['dyu', 'fr']
        )
    }
)

# Cast the dataset to the new schema
dataset = dataset.cast(features)
dataset
```
