### ISSUE TITLE
Multi-GPU training.

### ISSUE THREAD

**Issue by tongye98** [joeynmt/joeynmt#193]
**Describe the bug**
Not a bug, but a suggestion for enhancement.

The current solution for multi-gpu training adopts  `nn.DataParaller` in joeynmt-2.0.  
But the flaw of `nn.DataParallel` is obvious and Pytorch recommended useing `DistributedDataParallel`. 
I wonder to know whether the new multi-gpu training method is in process and can be seen in the next version aha.

**Comment by may-** [comment]
Hi @tongye98 

Thank you for asking!
The short answer is no, just because I cannot make it work. I was tried to integrate `DistributedDataParallel`, but for some reason I keep getting errors in my Single-Node Multi-GPU environment. Moreover, it's difficult to test multi-node distributed learning on my gpu cluster.

Your help is needed!!

**Comment by may-** [comment]
Reminder for myself: https://pytorch.org/tutorials/intermediate/ddp_tutorial.html

**Comment by Darwin99-debug** [comment]
Hi @may- , I used this tutorial(https://www.youtube.com/watch?v=-K3bZYHYHEA&list=PL_lsbAsL_o2CSuhUhJIiW0IkdT5C2wGWj)  to integrate DDP  and torch run in a Pytorch project and it worked well for me!

**Comment by may-** [comment]
Hi @Darwin99-debug,
Thank you for your comment!
Actually, we have been working on this (DDP) for a while. You can see our progress in the [ddp branch](https://github.com/joeynmt/joeynmt/tree/ddp) (#225)

Although it works, we are concerned that our current DDP implementation makes JoeyNMT less readable, less novice-friendly.
So we hesitate to integrate DDP to the main branch. Any comments and suggestions will be appreciated!

FYI @juliakreutzer

**Comment by may-** [comment]
see #225
