### ISSUE TITLE
JoeyNMT v1 procedure is no more compatible with JoeyNMT v2

### ISSUE THREAD

**Issue by Nibedita-Roy** [joeynmt/joeynmt#195]
Hi @Nibedita-Roy ,

`BOS_ID` was introduced in joeynmt v2.
I guess there is a version mismatch. Have you updated the joey  recently but keep using an old model, maybe?
Please check the version number.

We need a bit more context to reproduce your error. Which command did you use, when you've seen that error message above?

_Originally posted by @may- in https://github.com/joeynmt/joeynmt/issues/68#issuecomment-1237982588_

**Comment by Nibedita-Roy** [comment]
Hi @joeynmt 
Thank you for your reply.
My Context are given below,
# Do subword NMT
from os import path
os.environ["src"] = source_language # Sets them in bash as well, since we often use bash scripts
os.environ["tgt"] = target_language

# Learn BPEs on the training data.
os.environ["data_path"] = path.join("joeynmt", "data", source_language + target_language) # Herman! 
! subword-nmt learn-joint-bpe-and-vocab --input train.$src train.$tgt -s 3000 -o bpe.codes.3000 --write-vocabulary vocab.$src vocab.$tgt

# Apply BPE splits to the development and test data.
! subword-nmt apply-bpe -c bpe.codes.3000 --vocabulary vocab.$src < train.$src > train.bpe.$src
! subword-nmt apply-bpe -c bpe.codes.3000 --vocabulary vocab.$tgt < train.$tgt > train.bpe.$tgt

! subword-nmt apply-bpe -c bpe.codes.3000 --vocabulary vocab.$src < dev.$src > dev.bpe.$src
! subword-nmt apply-bpe -c bpe.codes.3000 --vocabulary vocab.$tgt < dev.$tgt > dev.bpe.$tgt
! subword-nmt apply-bpe -c bpe.codes.3000 --vocabulary vocab.$src < test.$src > test.bpe.$src
! subword-nmt apply-bpe -c bpe.codes.3000 --vocabulary vocab.$tgt < test.$tgt > test.bpe.$tgt

# Create directory, move everyone we care about to the correct location
! mkdir -p "$data_path"
! cp train.* "$data_path"
! cp test.* "$data_path"
! cp dev.* "$data_path"
! cp bpe.codes.3000 "$data_path"
! ls "$data_path"

# Also move everything we care about to a mounted location in google drive (relevant if running in colab) at gdrive_path
! cp train.* "$gdrive_path"
! cp test.* "$gdrive_path"
! cp dev.* "$gdrive_path"
! cp bpe.codes.3000 "$gdrive_path"
! ls "$gdrive_path"

# Create that vocab using build_vocab
! sudo chmod 777 joeynmt/scripts/build_vocab.py
! joeynmt/scripts/build_vocab.py joeynmt/data/$src$tgt/train.bpe.$src joeynmt/data/$src$tgt/train.bpe.$tgt --output_path joeynmt/data/$src$tgt/vocab.txt

# Some output
! echo "BPE Test language Sentences"
! tail -n 5 test.bpe.$tgt
! echo "Combined BPE Vocab"
! tail -n 10 joeynmt/data/$src$tgt/vocab.txt  # Herman


After Run the code I got below result

100% 3000/3000 [00:03<00:00, 899.13it/s] 
bpe.codes.3000	dev.bpe.as  test.bn	 train.as      train.bpe.bn
dev.as		dev.bpe.bn  test.bpe.as  train.bn
dev.bn		test.as     test.bpe.bn  train.bpe.as
bpe.codes.3000	dev.bpe.bn	  Target-as.txt      test.bpe.as  train.bpe.as
dev.as		models		  Target-as.txt.tok  test.bpe.bn  train.bpe.bn
dev.bn		Sorce-as.txt	  test.as	     train.as	  vocab.txt
dev.bpe.as	Sorce-as.txt.tok  test.bn	     train.bn
Traceback (most recent call last):
  File "joeynmt/scripts/build_vocab.py", line 16, in <module>
    from joeynmt.constants import (
ImportError: cannot import name 'BOS_ID' from 'joeynmt.constants' (/usr/local/lib/python3.7/dist-packages/joeynmt/constants.py)
BPE Test language Sentences
মূল তাস : ~ a
একটি ফাঁকা ভিত্তি স্ত@@ ূ@@ প
ভ@@ ি@@ ত্@@ তির উপর একটি ফাঁকা খাঁজ
ভ@@ ি@@ ত্@@ তির একটি ফাঁকা স্@@ ল@@ ট
একটি ফাঁকা খাঁজ
Combined BPE Vocab
tail: cannot open 'joeynmt/data/asbn/vocab.txt' for reading: No such file or directory

Please check the given error.

**Comment by may-** [comment]
Looking at your commands, you want to keep using Joeynmt v1.x, it seems.
Please reinstall JoeyNMT v1.x, i.e. `pip install git+https://github.com/joeynmt/joeynmt.git@1.5`. Then joey won't complain about `BOS_ID`.

Please also check if you use `joeynmt/scripts/build_vocab.py` in the same version, i.e. version 1.5: https://github.com/joeynmt/joeynmt/blob/1.5/scripts/build_vocab.py (not the latest version in the main branch)

---

I personally recommend to switch to JoeyNMT v2, then you don't have to prepare the BPE by yourself. You can just put non-tokanized raw text to the new version of `scripts/build_vocab.py`, it will take care of the BPE model creation for you. And you can specify the path to non-tokanized raw text in the config file. JoeyNMT internally applies the BPE tokenization during training / prediction.

**Comment by may-** [comment]
Are you sure you use the `build_vocab.py` script in version 1.5? Please download this:
https://github.com/joeynmt/joeynmt/blob/1.5/scripts/build_vocab.py
Not the one in the main repo currently.

**Comment by Nibedita-Roy** [comment]
Hi @joeynmt
Thank you. the code is worked..
No error detected.

**Comment by Nibedita-Roy** [comment]
Hi @joeynmt
Another error is coming After running below code

**# Train the model** 

!cd joeynmt; python3 -m joeynmt train configs/transformer_$src$tgt.yaml


**output**

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/joeynmt/joeynmt/__main__.py", line 3, in <module>
    from joeynmt.training import train
  File "/content/joeynmt/joeynmt/training.py", line 22, in <module>
    from torchtext.legacy.data import Dataset
ModuleNotFoundError: No module named 'torchtext.legacy'

**Comment by may-** [comment]
Most probably you should roll back your torch and torchtext installation. See https://github.com/joeynmt/joeynmt/issues/158#issuecomment-1120389462


Because of this torchtext dependency, I recommend to switch to joey v2. Is there any concrete reason why you want to stick to v1? If no, please consider to switch to joey v2.

**Comment by Nibedita-Roy** [comment]
Hi @joeynmt
Ok Thank You. I will try on joey v2

**Comment by may-** [comment]
Please note that the structure of `config.yaml` for v2 is very different from v1. You have to rewrite your `config.yaml` for v2.
Unlike joey v1, you should specify the input text path to raw text before bpe tokenization in v2.
`build_vocab.py` has also been heavily updated, the commandline arguments of the script are different.

**Comment by Nibedita-Roy** [comment]
@may- 
In Joey v1
Again Another error come after installed  torch and torchtext 


Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/joeynmt/joeynmt/__main__.py", line 48, in <module>
    main()
  File "/content/joeynmt/joeynmt/__main__.py", line 35, in main
    train(cfg_file=args.config_path, skip_test=args.skip_test)
  File "/content/joeynmt/joeynmt/training.py", line 803, in train
    cfg = load_config(cfg_file)
  File "/content/joeynmt/joeynmt/helpers.py", line 181, in load_config
    cfg = yaml.safe_load(ymlfile)
  File "/usr/local/lib/python3.7/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.7/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.7/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.7/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.7/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.7/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.7/dist-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "configs/transformer_asbn.yaml", line 13, column 15

**Comment by may-** [comment]
Could you please give me your config file? I guess your config file has some yaml syntax mistakes.

**Comment by Nibedita-Roy** [comment]
@may- 
Thank you it works. I modified  the mistakes
