### ISSUE TITLE
"AutocastCPU only supports Bfloat16" error when following rnn_reverse tutorial

### ISSUE THREAD

**Issue by matthew-burnard** [joeynmt/joeynmt#198]
**Describe the issue**
Using a CPU only version of Pytorch.
Attempting to follow the joeynmt tutorial (the rnn_reverse task).
Executing the step:
```python3 -m joeynmt train configs/reverse.yaml```
produces a warning about autocasting only support bfloat16 and then the following error (full warning and error trace bellow):
```RuntimeError: Currently, AutocastCPU only support Bfloat16 as the autocast_cpu_dtype```

**System :**
 - OS: Ubuntu 22.04.1 (Running in VirtualBox)
 - Python 3.10.6
 - Pytorch 1.12.1 (CPU only)

**Steps to reproduce the behavior:**
1. Follow install instructions [https://joeynmt.readthedocs.io/en/latest/install.html](https://joeynmt.readthedocs.io/en/latest/install.html)
2. Follow steps of tutorial [https://joeynmt.readthedocs.io/en/latest/tutorial.html](https://joeynmt.readthedocs.io/en/latest/tutorial.html)

**Logged output**
```
2022-10-27 15:33:46,845 - INFO - joeynmt.training - EPOCH 1
/home/dev/Documents/dev/jmnt/lib.python3.10/site-packages/torch/amp/autocast_mode.py:210: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
CPU Autocast only supports dtype of torch.bfloat16 currently.
  warnings.warn(error_message)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dev/Documents/dev/joeynmt/__main__.py", line 64, in <module>
    main()
  File "/home/dev/Documents/dev/joeynmt/__main__.py", line 44, in main
    train(cfg_file=args.config_path, skip_test=args.skip_test)
  File "C:\Users\m6urn\Documents\school\abbreviations-generation\jnmt\lib\site-packages\joeynmt\training.py", line 829, in train
    trainer.train_and_validate(train_data=train_data, valid_data=dev_data)
  File "/home/dev/Documents/dev/joeynmt/joeynmt/training.py", line 460, in train_and_validate
    norm_batch_loss = self._train_step(batch)
  File "/home/dev/Documents/dev/joeynmt/joeynmt/training.py", line 573, in _train_step
    with torch.autocast(device_type=self.device.type,
  File "/home/dev/Documents/dev/jmnt/lib/python3.10/site-packages/torch/amp//autocast_mode.py", line 234, in __enter__
    torch.set_autocast_cpu_dtype(self.fast_dtype)  # type: ignore[arg-type]
RuntimeError: Currently, AutocastCPU only support Bfloat16 as the autocast_cpu_dtype
```

**Comment by may-** [comment]
@matthew-burnard 

Could you please add `fp16: True` in the config file, i.e. `configs/transformer_reverse.yaml` or `configs/rnn_reverse.yaml`, and try to run the same train command again?

```yaml
training:
    [...]
    use_cuda: False
    print_valid_sents: [0, 3, 6]
    keep_best_ckpts: 2
    fp16: True                        # <- add this line!
```

Sorry, I haven't tested in CPU, and the tutorial is kind of outdated. We are working on the tutorial update for joey version 2, but it will take more time...

**Comment by may-** [comment]
reminder for myself:
- force to assign fp16 = True, if use_cuda = False
- update reverse task config files to use fp16
- update reverse task tutorial

**Comment by matthew-burnard** [comment]
Confirmed that this solves the problem on my end.

**Comment by may-** [comment]
Nice! Thank you for letting us know this. We will fix it.

**Comment by may-** [comment]
solved in https://github.com/joeynmt/joeynmt/pull/202
