### ISSUE TITLE
(enhancement) Deploying trained models on HuggingFace Space

### ISSUE THREAD

**Issue by sinaahmadi** [joeynmt/joeynmt#213]
Hi,

I am trying to deploy a few models that I have trained with JoeyNMT (thanks for this nice toolkit!). To avoid doing what may have been previously done, I was wondering if you can share some details about deploying the models as an app on [Huggingface Space](https://huggingface.co/spaces). Is there any similar project that I can get some ideas from?

Thanks.

**Comment by sinaahmadi** [comment]
I found a solution to deploy my models on HuggingFace. Future users can check it out at https://huggingface.co/spaces/SinaAhmadi/ScriptNormalization

**Comment by may-** [comment]
@sinaahmadi awesome! this must help a lot of users in the community. thank you for your contribution 👍
