### ISSUE TITLE
Link in Tutorial to Collab dead 

### ISSUE THREAD

**Issue by jowodo** [joeynmt/joeynmt#219]
**Describe the bug**
In the tutorial there is a dead link: https://github.com/joeynmt/joeynmt/blob/main/docs/source/tutorial.rst?plain=1#L9
The link points to collab note book at https://github.com/masakhane-io/masakhane-mt/ which does not exist anymore. 
I think it would be better to have a tutorial jupyter note book in this repo.

**Comment by may-** [comment]
Hello @jowodo,
Thank you for reporting the dead link!

There were historical reasons why we linked masakhane notebooks in our tutorial at that time (cf. https://arxiv.org/abs/2003.11529). Now, Masakhane side is also moving forward, less dependent to joeynmt. So we are trying to manage our own tutorials.

However, we are facing a manpower shortage to update our documentation. When we have time to improve our documentation, we'll make sure to get rid of the dead links.

**Comment by may-** [comment]
Please simply open a pull request.
You can open a new branch in your own fork and leave a comment there with a mention to me (@may-).
I'll back to you. Thanks a lot!

**Comment by may-** [comment]
fixed in v2.3.0 #225
