### ISSUE TITLE
Tutorial - Test Set Evaluation 

### ISSUE THREAD

**Issue by jowodo** [joeynmt/joeynmt#220]
**Describe the bug**
I follow the tutorial and at https://joeynmt.readthedocs.io/en/latest/tutorial.html#test-set-evaluation it fails 

**To Reproduce**
1. follow the tutorial until https://joeynmt.readthedocs.io/en/latest/tutorial.html#test-set-evaluation 
2. initial config file used: `configs/rnn_reverse.yaml` from the repo 
3. python3 -m joeynmt test reverse_model/config.yaml -o reverse_model/predictions

**Logged output**
```
2023-11-14 20:15:49,072 - INFO - root - Hello! This is Joey-NMT (version 2.2.1).
2023-11-14 20:15:49,072 - INFO - joeynmt.data - Building tokenizer...
2023-11-14 20:15:49,072 - INFO - joeynmt.tokenizers - src tokenizer: BasicTokenizer(level=word, lowercase=False, normalize=False, filter_by_length=(-1, 25), pretokenizer=none)
2023-11-14 20:15:49,072 - INFO - joeynmt.tokenizers - trg tokenizer: BasicTokenizer(level=word, lowercase=False, normalize=False, filter_by_length=(-1, 25), pretokenizer=none)
['dev', 'test']
test/data/reverse/train
2023-11-14 20:15:49,072 - INFO - joeynmt.data - Building vocabulary...
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/uni/Documents/masakhane/projects/jnmt/joeynmt.git/joeynmt/__main__.py", line 61, in <module>
    main()
  File "/Users/uni/Documents/masakhane/projects/jnmt/joeynmt.git/joeynmt/__main__.py", line 43, in main
    test(
  File "/Users/uni/Documents/masakhane/projects/jnmt/joeynmt.git/joeynmt/prediction.py", line 367, in test
    src_vocab, trg_vocab, _, dev_data, test_data = load_data(
  File "/Users/uni/Documents/masakhane/projects/jnmt/joeynmt.git/joeynmt/data.py", line 90, in load_data
    src_vocab, trg_vocab = build_vocab(data_cfg, dataset=train_data)
  File "/Users/uni/Documents/masakhane/projects/jnmt/joeynmt.git/joeynmt/vocabulary.py", line 264, in build_vocab
    src_vocab = _build_vocab(cfg["src"], dataset)
  File "/Users/uni/Documents/masakhane/projects/jnmt/joeynmt.git/joeynmt/vocabulary.py", line 241, in _build_vocab
    raise ValueError("Please provide a vocab file path or dataset.")
ValueError: Please provide a vocab file path or dataset.
```

**Expected behavior**
not to fail 

**System (please complete the following information):**
 - OS: MacOS 13.5.2 
 - Python Version: 3.9.6 

**Additional context**
in https://github.com/joeynmt/joeynmt/blob/v2.2/joeynmt/prediction.py#L350 we call `prediction.test()` with `datasets=["dev","test"]` 
then in https://github.com/joeynmt/joeynmt/blob/v2.2/joeynmt/data.py#L64 the dataset is only loaded/defined if `datasets` includes `"train"`, which is not the case since `prediction.test()` only defines `["dev","test"]` as dataset. 
Then, later in https://github.com/joeynmt/joeynmt/blob/v2.2/joeynmt/data.py#L86 the vocabulary is build with `dataset=train_data`.

Maybe the dataset which is build in data.load_data() should be name `dataset` (or similar) instead of train_data and a else statement added to the if expression at https://github.com/joeynmt/joeynmt/blob/v2.2/joeynmt/data.py#L66

**Comment by jowodo** [comment]
The solution was much easier! 
I got it running by changing https://github.com/joeynmt/joeynmt/blob/v2.2/joeynmt/data.py#L66 to 
```
    if train_path is not None:
```

**Comment by jowodo** [comment]
of course we could also change https://github.com/joeynmt/joeynmt/blob/v2.2/joeynmt/prediction.py#L350 to 
```
            data_cfg=cfg["data"], datasets=["train", "dev", "test"])
```

**Comment by may-** [comment]
@jowodo
Thank you for your effort! I'm very grateful for your help :)

When `prediction.py` is called, we assume that the vocab is already created and stored in `model_dir/{src, trg}_vocab.txt`, so, basically the `vocabulary.build_vocab()` func with `dataset=train_data` argument should never be called in the test mode.

This was the original idea of the data loading (designed even before I became the maintainer), so I'd like to keep the original design as is, and rather check the existence of the exported vocab files in the model dir before `data.load_data()` is called, and make sure not to enter in https://github.com/joeynmt/joeynmt/blob/v2.2/joeynmt/vocabulary.py#L233-L239 block at inference time.

Maybe we should explicitly mention something like this in the documentation:
> Please make sure that the vocab files (`src_vocab.txt` and `trg_vocab.txt`) exist in your `model_dir` before you call `joeynmt test config.yaml` command.

Will it solve your problem?
This weekend, I'll check the reverse task in the tutorial and try to figure out why the vocab file existence check in https://github.com/joeynmt/joeynmt/blob/v2.2/joeynmt/vocabulary.py#L256-L262 didn't work.

**Comment by jowodo** [comment]
Hi, thanks for the detailed explanation and quick reply! I now see why my proposed solutions are not really working. 

I think that the vocab is not loaded because it is missing from the created config `reverse_model/config.yaml`, but `reverse_model/src_vocab.txt` and `reverse_model/trg_vocab.txt` are present after training. I was not sure if this is what is needed since somewhere a different naming scheme (`*.vocab`) has been mentioned. (I think in `configs/wmt17_ende_bpe.yaml` and `configs/jparacrawl_enja_sp.yaml`) .

**Comment by may-** [comment]
there are two cases:

## case 1:
1. run `scripts/build_vocab.py` -> vocab files are generated (let's say in `somewhere/vocab_path/vocab.txt`)
2. specify the generated vocab file paths (`somewhere/vocab_path/vocab.txt`), and run training -> specified vocab files will be used in training
3. keep the vocab file paths (`somewhere/vocab_path/vocab.txt`) in cfg, and run testing -> specified vocab files will be used in testing

In case of joint vocab with huggingface's datasets, follow this workflow.

## case 2:
1. run training without specifying vocab file path -> joey constructs vocab during training, vocab files will be saved in `model_dir/{src|trg}_vocab.txt`
2. specify the vocab file paths (`model_dir/{src|trg}_vocab.txt`), and run testing -> vocab files in model_dir will be used in testing

In case you use the data from `scripts/get_iwslt14_bpe.sh`, follow this workflow. Because the bash script creates joint vocab within the script, you don't have to run `scripts/build_vocab.py`.

In general, we recommend to use absolute path in stead of relative path in cfg to avoid file-not-found error.
