### ISSUE TITLE
Assertion statements in decoder breaks the code by training with lstms

### ISSUE THREAD

**Issue by Sariyusha** [joeynmt/joeynmt#24]

**Comment by Sariyusha** [comment]
assert hidden.shape[0] == self.num_layers 
AttributeError: 'tuple' object has no attribute 'shape'

The code runs by using the old lines in the config file 'type: "lstm"' (instead of 'rnn_type: "lstm"').

**Comment by juliakreutzer** [comment]
Fixed.
