### ISSUE TITLE
`init_state` for Decoder 

### ISSUE THREAD

**Issue by adarsh-kr** [joeynmt/joeynmt#51]
**Describe the bug**
`init_state` for Decoder in case of LSTM rnn, should take `context` and `hidden` tensor. However, `init_hidden` returns `(hidden, hidden)`. Shouldn't we change this to `(hidden, context)` ?

Reference: https://github.com/joeynmt/joeynmt/blob/master/joeynmt/decoders.py#L422

**Comment by juliakreutzer** [comment]
Please check out the discussion in this issue: https://github.com/joeynmt/joeynmt/issues/13
