### ISSUE TITLE
UnicodeEncodeError on Windows

### ISSUE THREAD

**Issue by voslucas** [joeynmt/joeynmt#62]
Python 3.7 ; Windows ;

I get an error when trying to train a network on deen_bpe downloaded dataset task on a Windows machine.

**Error**
UnicodeEncodeError: 'charmap' codec can't encode character '\u201f' in position 0: character maps to <undefined>

**Suggested solution**
In vocabulary.py the `with open(file, "r")` and `with open(file,"w")` lacks the `encoding="utf-8"` argument.

**Comment by juliakreutzer** [comment]
Hi @voslucas 
it seems like this is caused by the console not being able to print utf8. Can you try setting the PYTHONIOENCODING variable? -> http://www.tiernok.com/posts/python-3-6-unicode-output-for-windows-console.html

Your suggested solution doesn't hurt anyway ;)

**Comment by voslucas** [comment]
I changed to source as mentioned in solution! Which worked ;) Thanx!
