### ISSUE TITLE
will you support RL(policy gradient or actor critic)?

### ISSUE THREAD

**Issue by zhaoguangxiang** [joeynmt/joeynmt#64]
Missing RL models

**Comment by juliakreutzer** [comment]
Policy Gradient will probably be integrated here. Other RL algorithms are not part of the minimalist set of features, so they won't go into the main branch.
Let us know if you're keen on implementing any of those.

**Comment by zhaoguangxiang** [comment]
> Policy Gradient will probably be integrated here. Other RL algorithms are not part of the minimalist set of features, so they won't go into the main branch.
> Let us know if you're keen on implementing any of those.

I am working on  transfering recent RL algorithms to  NMT setting.   Why did NLP researchers  still use policy gradient, is this because the PG is much better than other methods?

**Comment by juliakreutzer** [comment]
Cool, all the best for your projects! 
Regarding Policy Gradient, it is (1) very simple to implement and train and (2) deals well with large action spaces and (3) does not require expensive computations. Actor-critic algorithms have been proposed as well, e.g. in [Bahdanau et al. 2017](https://arxiv.org/abs/1607.07086) or [Nguyen et al. 2017](https://www.aclweb.org/anthology/D17-1153), but you'll notice that they require more complex training regimes and models.
