### ISSUE TITLE
Remove Torchtext dependency

### ISSUE THREAD

**Issue by juliakreutzer** [joeynmt/joeynmt#7]
For more transparent and flexible data handling, batching and vocabulary building.

The goal would be to be as efficient as torchtext, but have more flexibility for the following use cases:
- loading data without the target side (e.g. for inference)
- an interactive mode where the data cannot be loaded from a file 
- shared vocabularies, e.g. for source and target side, for multiple encoders or decoders
- for multi-tasking where more than one data set is used

**Comment by bastings** [comment]
- Support for large (>10GB) data sets.

**Comment by juliakreutzer** [comment]
- avoid loading training data during testing

**Comment by juliakreutzer** [comment]
working on it

**Comment by may-** [comment]
torchtext 0.10.0 was released and torchtext.legacy is retireing. I think we should consider a plan to get rid of torchtext. How do you think @juliakreutzer ?

**Comment by may-** [comment]
I removed torchtext completely. Could anyone check it, please? I hesitate to open a pull requiest, because the change is kind of huge.

https://github.com/may-/joeynmt/tree/multi-gpu

my environment:

- python 3.9
- cuda 10.2
- pytorch 1.9.0
- numpy 1.20.1
- pylint 2.9.6

**Comment by juliakreutzer** [comment]
Done by @may- in v2.0 :partying_face:
