### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by qmpham** [joeynmt/joeynmt#76]
Does joeynmt support multi-gpu training? After reading the source-code, I've found none code distributing graphs in different devices. I might be wrong. Thanks for the work!

**Comment by bastings** [comment]
Hi! No, Joey NMT does not support that at the moment.
If there is a simple way to incorporate multi-GPU training we are happy to receive a PR for it.

**Comment by juliakreutzer** [comment]
I'm going to close this issue for now. We can re-open it if it becomes high priority. I added the question to the FAQs.
