### ISSUE TITLE
embedding dropout

### ISSUE THREAD

**Issue by raphael-sch** [joeynmt/joeynmt#88]
Make clear in documentation and small.yaml that encoder (and decoder?) embedding section takes a separate dropout argument and defaults to encoder dropout argument if missing.

Will send a pull request myself eventually and just document all issues I find along the way of setting joey up for me.

**Comment by juliakreutzer** [comment]
great, thanks!

**Comment by juliakreutzer** [comment]
@raphael-sch ping :wink: any progress on that?

**Comment by juliakreutzer** [comment]
@raphael-sch closing it for now, please feel free to re-open if you send that PR to link it to this issue.
