### ISSUE TITLE
Example scripts repo

### ISSUE THREAD

**Issue by bricksdont** [joeynmt/joeynmt#89]
Hi Julia and Joost!

Currently testing joeynmt for our MT class, verdict: awesome! Planning to use it for several exercises.

For the class I've put together example scripts in a small repo here:

https://github.com/bricksdont/joeynmt-toy-models

Just a collection of scripts that show how to make a virtualenv, install packages, download data, preprocess, train and evaluate. Your documentation mentions all of this of course, but the info is more distributed.

If this is useful in any way feel free to link to this somewhere. Otherwise, feel free to close :)

**Comment by juliakreutzer** [comment]
That's awesome!! Thanks so much for creating this repo and sharing it with us :100: 
I'll link it from the README and docs. 

Let us know how the MT class is going and what the experience with Joey NMT is like!

**Comment by juliakreutzer** [comment]
Added links on readme and docs.

**Comment by bastings** [comment]
Thanks Mathias, looking forward to hear how it went with the class.
