### ISSUE TITLE
batch_multiplier NotImplementedError (Transformer)

### ISSUE THREAD

**Issue by Dixxy** [joeynmt/joeynmt#90]
Hello, I'm testing JoeyNMT to see if it works for my translation studies master's thesis (right now looking at different toolkits with which to traini several patent translation models in EN-JP)

**Describe the bug**

When trying to run training on with batch_multiplier set to 4 instead of 1 training fails before starting.

Using the same settings, but with "batch_multiplier 1" starts training.

**To Reproduce**
1. Task description: Training Patent Transformer NMT on trainingcorpus with approx 680.000 lines in both src and tgt.

2. configuration file [ntc7otrans.yaml]

> name: "transformer"
> 
> data:
>     src: "jp.tk"
>     trg: "en.tk"
>     train: "/home/chris/NMT/data/ntc7o/traino"
>     dev:   "/home/chris/NMT/data/ntc7o/val"
>     test:  "/home/chris/NMT/data/ntc7o/test"
>     level: "word"
>     lowercase: False
>     max_sent_length: 100
>     src_vocab: "/home/chris/NMT/data/ntc7o/joeyNMT/vocabo.jp.tk"
>     trg_vocab: "/home/chris/NMT/data/ntc7o/joeyNMT/vocabo.en.tk"
> 
> testing:
>     beam_size: 5
>     alpha: 1.0
> 
> training:
>     random_seed: 3435
>     optimizer: "adam"
>     normalization: "tokens"
>     adam_betas: [0.9, 0.999]
>     scheduling: "plateau"
>     patience: 8
>     decrease_factor: 0.7
>     loss: "crossentropy"
>     learning_rate: 0.0002
>     learning_rate_min: 0.00000001
>     weight_decay: 0.0
>     label_smoothing: 0.1
>     batch_size: 512
>     batch_type: "token"
>     eval_batch_size: 32
>     eval_batch_type: "token"
>     **batch_multiplier: 4**
>     early_stopping_metric: "ppl"
>     epochs: 100
>     validation_freq: 5000
>     logging_freq: 100
>     eval_metric: "bleu"
>     model_dir: "models/ntc7otrans"
>     overwrite: True
>     shuffle: True
>     use_cuda: True
>     max_output_length: 100
>     print_valid_sents: [0, 1, 2, 3]
>     keep_last_ckpts: 5
> 
> model:
>     initializer: "xavier"
>     bias_initializer: "zeros"
>     init_gain: 1.0
>     embed_initializer: "xavier"
>     embed_init_gain: 1.0
>     tied_embeddings: False
>     tied_softmax: True
>     encoder:
>         type: "transformer"
>         num_layers: 6
>         num_heads: 8
>         embeddings:
>             embedding_dim: 512
>             scale: True
>             dropout: 0.
>         # typically ff_size = 4 x hidden_size
>         hidden_size: 512
>         ff_size: 2048
>         dropout: 0.1
>     decoder:
>         type: "transformer"
>         num_layers: 6
>         num_heads: 8
>         embeddings:
>             embedding_dim: 512
>             scale: True
>             dropout: 0.
>         # typically ff_size = 4 x hidden_size
>         hidden_size: 512
>         ff_size: 2048
>         dropout: 0.1
> 

3. code call [python3 -m joeynmt train configs/ntc7otrans.yaml]

**Logged output**

> 2020-03-27 13:49:27,311 Data set sizes: 
> 	train 682849,
> 	valid 914,
> 	test 899
> 2020-03-27 13:49:27,311 First training example:
> 	[SRC] そして 、 上記 関係 を 少なくとも 10 万 枚 通 紙 し て も 維持 し なけれ ば なら ない 。
> 	[TRG] This relation must be maintained even after passing at least 100,000 sheets .
> 2020-03-27 13:49:27,312 First 10 words (src): (0) <unk> (1) <pad> (2) <s> (3) </s> (4) 、 (5) の (6) に (7) １ (8) を (9) 。
> 2020-03-27 13:49:27,312 First 10 words (trg): (0) <unk> (1) <pad> (2) <s> (3) </s> (4) the (5) , (6) . (7) of (8) a (9) is
> 2020-03-27 13:49:27,312 Number of Src words (types): 67918
> 2020-03-27 13:49:27,312 Number of Trg words (types): 89223
> 2020-03-27 13:49:27,313 Model(
> 	encoder=TransformerEncoder(num_layers=6, num_heads=8),
> 	decoder=TransformerDecoder(num_layers=6, num_heads=8),
> 	src_embed=Embeddings(embedding_dim=512, vocab_size=67918),
> 	trg_embed=Embeddings(embedding_dim=512, vocab_size=89223))
> 2020-03-27 13:49:27,378 EPOCH 1
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/chris/NMT/joeyNMT/joeynmt/__main__.py", line 41, in <module>
>     main()
>   File "/home/chris/NMT/joeyNMT/joeynmt/__main__.py", line 29, in main
>     train(cfg_file=args.config_path)
>   File "/home/chris/NMT/joeyNMT/joeynmt/training.py", line 650, in train
>     trainer.train_and_validate(train_data=train_data, valid_data=dev_data)
>   File "/home/chris/NMT/joeyNMT/joeynmt/training.py", line 317, in train_and_validate
>     if self.batch_multiplier > 1 and i == len(train_iter) - \
>   File "/home/chris/.virtualenvs/joeyNMT/lib/python3.6/site-packages/torchtext/data/iterator.py", line 136, in __len__
>     raise NotImplementedError
> NotImplementedError

**Expected behavior**
Training should start and wait for 4 batches to complete before update.

**System (please complete the following information):**
 - OS: Manjaro Linux 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=19.0.2
DISTRIB_CODENAME=Kyria
DISTRIB_DESCRIPTION="Manjaro Linux"
 - CPU / GPU
CPU: Core i7 2600k
GPU: RTX 2060 6GB vram
 - Python Version 
3.6.6

**Additional context**

**Comment by bastings** [comment]
Hi, thanks for filing the issue!

It looks like this PR #81 broke things.

From a quick look, I think it is simply not possible to do `len(train_iter)` as is done in `training.py` on line 317. 

@B-Czarnetzki are you around by any chance?

**Comment by bastings** [comment]
@Dixxy as a quick fix, could you try removing lines 315-321 from training.py?

**Comment by Dixxy** [comment]
@bastings Hello! Thanks for the quick reply. Removing the lines resolves the issue, but I had to reduce batch-size from 512 to 256 to fit it into memory.

Generally, memory-consumption is quite high compared to OpenNMT (py/tf) running the same/similar Transformer architecture. Am I missing something in the hyper-parameters, or is this expected at the moment?

**Comment by B-Czarnetzki** [comment]
@bastings Hello! 
So the problem with using len(train_iter) seems to be the __len__ definition of the torchtext iterator https://github.com/pytorch/text/blob/master/torchtext/data/iterator.py: 

 def __len__(self):
        if self.batch_size_fn is not None:
            raise NotImplementedError
        return math.ceil(len(self.dataset) / self.batch_size)

It doesn't work if  self.batch_size_fn is used, which is the case in joeyNMT for batch_type: "token"

Your workaround of commenting out the lines 315-321 in training.py does fix this issue, but it reverts the bug fix described in d184815. 
When fixing this i didn't consider the batch_type: "token" case. 

I'll look into a fix

**Comment by juliakreutzer** [comment]
@Dixxy sorry to hear you're having problems with memory. 6 GB is relatively small, we trained the benchmark models with more memory (10G-20G), which is why the standard configurations will probably not work for you. 
You could try to see how far you get with a [Google Colab](https://colab.sandbox.google.com/notebooks/intro.ipynb#recent=true), since the data is relatively small. There you can use a 12 GB GPU for 12h for free and save the models on Google Drive. Here's an [example notebook](https://github.com/masakhane-io/masakhane/blob/master/starter_notebook-custom-data.ipynb) - you can probably skip the pre-processing.
What you can do in addition to reducing the batch size, is reducing the `max_output_length` or try GRUs/LSTMs, they usually take less memory. Both might result in drop in quality, though.

Thanks @bastings and @B-Czarnetzki for your quick reaction and solutions.

**Comment by B-Czarnetzki** [comment]
So i thought about how to fix the last batch in epoch problem (d184815) for batch_multiplier for the batch_type: "token" case. If it is possible i can't figure it out right now. To compute a "current_batch_multiplier" that fits the number of leftover batches, there seems to be no way around needing to know the number of effective batches the train_iter generates in an epoch. The problem is that this isn't deterministic for a shuffled dataset. The number of effective batches can be different every time due to padding. So unless we do some exspensive computation at the start of each epoch to get the number of effective batches, there's no way to know when, and how to compute the "current_batch_multiplier" to fit the leftover examples. 

So for now maybe just add a "and self.batch_type =="sentence" in line 317 ? 
But maybe someone else has an idea?

**Comment by juliakreutzer** [comment]
Thanks for looking into this @B-Czarnetzki! I propose we just skip the leftovers in this case. Mayumi also mentioned this issue and pointed me to huggingface BERT implementation: https://github.com/huggingface/transformers/blob/a8e3336a850e856188350a93e67d77c07c85b8af/templates/adding_a_new_example_script/run_xxx.py#L175

**Comment by juliakreutzer** [comment]
@B-Czarnetzki what do you think about just skipping the leftover batches?

**Comment by B-Czarnetzki** [comment]
@juliakreutzer Sorry for not responding to your original proposal. I just kinda took it as the final decision.
Should be a good solution. The easiest way to do this would probably be to just add "self.optimizer.zero_grad()" at the start of every epoch. This way the gradients of the leftover batches still get computed, which is a small unnecessary overhead, but the model never gets updated with them.

I just glanced over the code you sent and i think they are doing it the same way.

Doing it in any other way would pose the same problems as explained in https://github.com/joeynmt/joeynmt/issues/90#issuecomment-605927043

As far as i know skipping the last batch, that doesn't have the same batch size, is not uncommon. Probably somewhat needed if no batch loss normalizaton is done, isn't it.

**Comment by juliakreutzer** [comment]
@B-Czarnetzki cool, happy we found a solution! Would you be able to implement this? Would be very appreciated :+1:
